version: '3'
services:
  ollama:
    volumes:
      - './ollama:/root/.ollama'
    ports:
      - '11434:11434'
    container_name: ollama
    image: 'ollama/ollama:latest'
    environment:
      - OLLAMA_ORIGINS=*
volumes:
  ollama:
    external: false